---
title: "Factors influencing duration of =no"
output: html_document
---

## 1. Load Data
```{r}
rm(list=ls())
load("output/SumiFoc.RData")
```

## 2. Subset data for word before =no
```{r}
library(Rmisc)
library(ggplot2)
# Get only =no tokens
SumiFoc.word <- subset(SumiFoc.df, Word != "no" & Word != "akijeu" & Word != "ha" & Word != "zU" & Word != "ani" & Word != "cheni")
#View(SumiFoc.word)
SumiFoc.word.wide <- subset(SumiFoc.wide, Word != "no" & Word != "akijeu" & Word != "ha" & Word != "zU" & Word != "ani" & Word != "cheni")
#View(SumiFoc.word.wide)
```

# 3.1. Effect of only focus condition on duration of word before =no
```{r}
# Compare durations across focus conditions (collapsed for tone category)
SumiFoc.word.dur.summ1 <- summarySE(SumiFoc.word.wide, "Dur", groupvars = "Focus", na.rm = TRUE)
SumiFoc.word.dur.summ1

SumiFoc.word.dur1 <- lm(Dur ~ Focus, data = SumiFoc.word.wide)
summary(SumiFoc.word.dur1)

# Plot differences in duration across focus conditions (collapsed for tone category)
#plot(SumiFoc.word.wide$Focus, SumiFoc.word.wide$Dur, xlab = "Focus condition", ylab = "Duration (ms)", main = expression(paste("Duration of ", italic("=no"), " by focus condition")))

library(ggplot2)
SumiFoc.word.dur.plot1 <- ggplot(data = SumiFoc.word.wide, aes(x = Focus, fill = Focus, y = Dur)) +
  geom_boxplot() +
  theme_bw() +
  labs(x = "Focus condition", y = "Duration (s)", title = (expression(paste("Duration of word preceding ", italic("=no"), ", by focus condition")))) +
  theme(plot.title = element_text(hjust = 0.5))
SumiFoc.word.dur.plot1
dev.copy(png, "figures/SumiFoc_word_focus_dur.png")
dev.off()
```

# 3.2 Effect of focus condition and predicate on duration of word before =no
```{r}
## Check for interaction with tone category of preceding word [not expected]
# Summarize by Focus Condition & Tone Category of preceding word
SumiFoc.word.dur.summ2 <- summarySE(SumiFoc.word.wide, "Dur", groupvars = c("Focus", "Predicate"), na.rm = TRUE)
SumiFoc.word.dur.summ2

SumiFoc.word.dur2 <- lm(Dur ~ Focus * Predicate, data = SumiFoc.word.wide)
summary(SumiFoc.word.dur2)

# Plot differences in duration across focus condition and predicate
SumiFoc.word.dur.plot2 <- ggplot(data = SumiFoc.word.wide, aes(x = Focus, fill = Predicate,  y = Dur)) +
  geom_boxplot() +
  theme_bw() +
  labs(x = "Focus condition", y = "Duration (s)", title = (expression(paste("Duration of word preceding ", italic("=no"), ", by focus condition and predicate")))) +
   scale_fill_discrete(name="Predicate",
                         breaks=c("chase", "sleep", "big"),
                         labels=c("chase", "sleep", "(be) the big one")) +
  theme(plot.title = element_text(hjust = 0.5))
SumiFoc.word.dur.plot2
dev.copy(png, "figures/SumiFoc_word_focuspred_dur.png")
dev.off()
```

# 3.3 Effect of focus condition and tone category of last syll on duration of word before =no
```{r}
## Check for interaction with tone category of preceding word [not expected]
# Summarize by Focus Condition & Tone Category of preceding word
SumiFoc.word.dur.summ3 <- summarySE(SumiFoc.word.wide, "Dur", groupvars = c("Focus", "ToneCondition"), na.rm = TRUE)
SumiFoc.word.dur.summ3

SumiFoc.word.dur3 <- lm(Dur ~ Focus * ToneCondition, data = SumiFoc.word.wide)
summary(SumiFoc.word.dur3)

# Plot differences in duration across focus condition and preceding tone category
SumiFoc.word.dur.plot3 <- ggplot(data = SumiFoc.word.wide, aes(x = Focus, fill = ToneCondition,  y = Dur)) +
  geom_boxplot() +
  theme_bw() +
  labs(x = "Focus condition", y = "Duration (s)", title = (expression(paste("Duration of word preceding ", italic("=no"), ", by focus condition and tone category of last syllable")))) +
  scale_fill_discrete(name="Tone of\npreceding syll",
                         breaks=c("H", "M", "L"),
                         labels=c("High", "Mid", "Low")) +
  theme(plot.title = element_text(hjust = 0.5))
SumiFoc.word.dur.plot3
dev.copy(png, "figures/SumiFoc_word_focustone_dur.png")
dev.off()
```

## 4. Save RData
```{r}
save.image(file="output/SumiFoc-no_dur.RData")
```
