---
title: "Factors influencing duration of =no"
output: html_document
---

## 1. Load Data
```{r}
#rm(list=ls())
load("output/SumiFoc.RData")
```

## 2. Subset data for last syllable before =no
```{r}
library(Rmisc)
library(ggplot2)
# Get only =no tokens
SumiFoc.tone <- subset(SumiFoc.df, Tone == "H"| Tone == "M"| Tone == "L")
#View(SumiFoc.tone)
SumiFoc.tone.wide <- subset(SumiFoc.wide, Tone == "H"| Tone == "M"| Tone == "L")
#View(SumiFoc.tone.wide)
```

# 3.1. Effect of only focus condition on duration of last syllable before =no
```{r}
# Compare durations across focus conditions (collapsed for tone category)
SumiFoc.tone.dur.summ1 <- summarySE(SumiFoc.tone.wide, "Dur", groupvars = "Focus", na.rm = TRUE)
SumiFoc.tone.dur.summ1

SumiFoc.tone.dur1 <- lm(Dur ~ Focus, data = SumiFoc.tone.wide)
summary(SumiFoc.tone.dur1)

# Plot differences in duration across focus conditions (collapsed for tone category)
#plot(SumiFoc.tone.wide$Focus, SumiFoc.tone.wide$Dur, xlab = "Focus condition", ylab = "Duration (ms)", main = expression(paste("Duration of ", italic("=no"), " by focus condition")))

library(ggplot2)
SumiFoc.tone.dur.plot1 <- ggplot(data = SumiFoc.tone.wide, aes(x = Focus, fill = Focus, y = Dur)) +
  geom_boxplot() +
  theme_bw() +
  labs(x = "Focus condition", y = "Duration (s)", title = (expression(paste("Duration of syllable preceding ", italic("=no"), ", by focus condition")))) +
  theme(plot.title = element_text(hjust = 0.5))
SumiFoc.tone.dur.plot1
dev.copy(png, "figures/SumiFoc_lastsyll_focus_dur.png")
dev.off()
```

# 3.2 Effect of focus condition and predicate on duration of =no
```{r}
## Check for interaction with tone category of preceding word [not expected]
# Summarize by Focus Condition & Tone Category of preceding word
SumiFoc.tone.dur.summ2 <- summarySE(SumiFoc.tone.wide, "Dur", groupvars = c("Focus", "Predicate"), na.rm = TRUE)
SumiFoc.tone.dur.summ2

SumiFoc.tone.dur2 <- aov(Dur ~ Focus * Predicate, data = SumiFoc.tone.wide)
summary(SumiFoc.tone.dur2)

# Plot differences in duration across focus condition and predicate
SumiFoc.tone.dur.plot2 <- ggplot(data = SumiFoc.tone.wide, aes(x = Focus, fill = Predicate,  y = Dur)) +
  geom_boxplot() +
  theme_bw() +
  labs(x = "Focus condition", y = "Duration (s)") + #title = (expression(paste("Duration of syllable preceding ", italic("=no"), ", by focus condition and predicate")))) +
  theme(axis.title = element_text(size = 16)) +
  theme(axis.text = element_text(size = 14)) +
  ylim(0, 0.20) +
    scale_fill_brewer(name="Sentence type",
          breaks=c("chase", "sleep", "big"),
          labels=c("transitive 'chase'", "intransitive 'sleep'", "verbless 'bigger'"),
          palette="Set2") +
  theme(legend.justification = c(1,0.99), legend.position = c(1,0.99)) +
  theme(legend.title = element_text(size = 16)) +
  theme(legend.text = element_text(size = 14)) +
  theme(plot.title = element_text(hjust = 0.5))
SumiFoc.tone.dur.plot2

#Save as PNG file
png(file = "figures/SumiFoc_no50_focustone_f0-color.png", width = 500, height = 450, res = 72)
SumiFoc.tone.dur.plot2
dev.off()
```

# 3.3 Effect of focus condition and tone category of preceding syll on duration of =no
```{r}
## Check for interaction with tone category of preceding word [not expected]
# Summarize by Focus Condition & Tone Category of preceding word
SumiFoc.tone.dur.summ3 <- summarySE(SumiFoc.tone.wide, "Dur", groupvars = c("Focus", "ToneCondition"), na.rm = TRUE)
SumiFoc.tone.dur.summ3

SumiFoc.tone.dur3 <- lm(Dur ~ Focus * ToneCondition, data = SumiFoc.tone.wide)
summary(SumiFoc.tone.dur3)

# Plot differences in duration across focus condition and preceding tone category
SumiFoc.tone.dur.plot3 <- ggplot(data = SumiFoc.tone.wide, aes(x = Focus, fill = ToneCondition,  y = Dur)) +
  geom_boxplot() +
  theme_bw() +
  labs(x = "Focus condition", y = "Duration (s)", title = (expression(paste("Duration of syllable preceding ", italic("=no"), ", by focus condition and tone category of preceding syllable")))) +
  scale_fill_discrete(name="Tone of\npreceding syll",
                         breaks=c("H", "M", "L"),
                         labels=c("High", "Mid", "Low")) +
  theme(plot.title = element_text(hjust = 0.5))
SumiFoc.tone.dur.plot3
dev.copy(png, "figures/SumiFoc_lastsyll_focustone_dur.png")
dev.off()

```

## 4. Save RData
```{r}
save.image(file="output/SumiFoc-no_dur.RData")
```
